Adding open-source code for the PRECISION paper
p4lang/p4-applications pull request #51
Opened 2018-08-10 02:13 UTC by chenxiaoqino

Submitting P4 code accompanying our recent paper _Efficient Measurement on Programmable
Switches Using Probabilistic Recirculation_, to appear in ICNP'18.

2018-08-11 00:13 UTC, mhira1 commented on research_projects/PRECISION/README.md
> +This example uses SrcIP/DstIP pair as flow ID, but you're more than welcomed to change to other flow ID definition.
Typo: "welcomed" -> "welcome"

2018-08-11 00:13 UTC, mhira1 commented on research_projects/PRECISION/LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
Please move this LICENSE file under src

2018-08-11 00:13 UTC, mhira1 commented on research_projects/PRECISION/src/precision.p4
> +         standard_metadata.egress_spec = 9w3 - standard_metadata.ingress_port;
Please add a comment here. What is the expression on the right hand side doing?

2018-08-11 00:13 UTC, mhira1 commented on research_projects/PRECISION/src/entries_naive.txt
> +			(64w0b0000000000000000000000000000000000000000000000000000000000000011 &&& 64w0b1111111111111111111111111111111111111111111111111111111111111110, 64w0 &&& 64w0b000000000000000000000000000000000000
.txt sounds unusual for an include file. Can you name it as .h or .p4?

2018-08-11 00:13 UTC, mhira1 commented on research_projects/PRECISION/src/entries_better.txt
> +
Can you rename to .h or .p4?

2018-08-11 00:48 UTC, chenxiaoqino commented
@mhira1 Thanks for the comments, I've fixed the files accordingly.

2018-08-13 15:15 UTC, chenxiaoqino commented
Done adding paper link and citation information

2018-08-13 22:06 UTC, mhira1 reviewed
Danny, this is good to commit to the repository. However, can you please squash all 11 commits into 1 commit?

2018-08-13 22:07 UTC, chenxiaoqino commented
Hi Mukesh,

Sure, let me figure out how.

On Mon, Aug 13, 2018 at 6:06 PM Mukesh Hira <notifications@github.com>
wrote:

> *@mhira1* commented on this pull request.
>
> Danny, this is good to commit to the repository. However, can you please
> squash all 11 commits into 1 commit?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/p4lang/p4-applications/pull/51#pullrequestreview-145854791>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABvpXgUzU-EQbfB-uWKOxQ15YnhFoVr_ks5uQfhSgaJpZM4V3ero>
> .
>

2018-08-13 22:17 UTC, chenxiaoqino commented
I have squashed all changes into one commit. Can you check if that's been done correctly? Thanks!

2018-08-13 22:21 UTC, mhira1 approved these changes
Thanks for squashing into one commit. Looks good.

2018-08-13 22:46 UTC, jnfoster requested changes
Please remove the license file. All contributions to P4 are done under the Apache2 license, per your signed member agreement.

2018-08-13 22:49 UTC, jnfoster commented
@chenxiaoqino: just to confirm since I am traveling, are you or your employer a P4 member?

2018-08-13 22:51 UTC, chenxiaoqino commented
I believe yes. Although not all authors of the paper are, I myself am
affiliated with Princeton University. I write and open-source the code on
my own behalf.

On Mon, Aug 13, 2018 at 6:49 PM Nate Foster <notifications@github.com>
wrote:

> @chenxiaoqino <https://github.com/chenxiaoqino>: just to confirm since I
> am traveling, are you or your employer a P4 member?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/p4lang/p4-applications/pull/51#issuecomment-412691461>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABvpXtoUmB27R_o8mJcH7ORJMIOdyQ2Zks5uQgJqgaJpZM4V3ero>
> .
>

2018-08-13 23:03 UTC, chenxiaoqino commented
@jnfoster Done.

2018-08-14 00:44 UTC, jklr commented
@chenxiaoqino  how about adding your name and contact email into the README?

2018-08-14 00:51 UTC, chenxiaoqino commented
@jklr Sure

2018-08-14 01:04 UTC, jklr approved these changes

2018-08-15 22:56 UTC, merged